name: Update

on: 
  repository_dispatch:
  workflow_dispatch:

# 定时触发编译
  schedule:
    - cron: 0 */1 * * *

# 点赞☆Star触发编译
#  watch:
#    types: [started]

jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Repository
      uses: actions/checkout@v4

    - name: Set git
      run : |
        git config --global user.email "jsjson@163.com"
        git config --global user.name "xiangfeidexiaohuo"
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 1
        keep_minimum_runs: 0  
        
    - name: Update
      run: |

        rm -rf ./luci-app-pushbot
        rm -rf ./luci-app-wechatpush
        # rm -rf ./luci-app-easymesh
        rm -rf ./luci-app-ikoolproxy
        rm -rf ./luci-app-unblockneteasemusic
        rm -rf ./linkease/*   
        rm -rf ./op-oaf
        rm -rf ./patch/wall/*
        rm -rf ./patch/wall-luci/luci-app-passwall
        rm -rf ./patch/wall-luci/luci-app-passwall2
        rm -rf ./patch/wall-luci/luci-app-ssr-plus
        rm -rf ./patch/wall-luci/luci-app-openclash
        rm -rf ./patch/wall-luci/luci-app-nikki
        rm -rf ./patch/wall-luci/nikki
        rm -rf ./patch/wall-luci/luci-app-momo
        rm -rf ./patch/wall-luci/momo
        rm -rf ./patch/wall-luci/luci-app-homeproxy
        rm -rf ./theme/luci-theme-argon
        # rm -rf ./luci-app-oled
        rm -rf ./op-lucky/*
        rm -rf ./op-daed/*
        rm -rf ./op-mosdns/*
        # rm -rf ./op-smartdns/*
        rm -rf ./op-openlist2/*
        rm -rf ./op-qB/*
        rm -rf ./op-easytier/*


        git clone https://github.com/linkease/istore-packages ./op-qB/tmp
        cp -af ./op-qB/tmp/luci-app-qbittorrent ./op-qB/
        cp -af ./op-qB/tmp/qBittorrent-static ./op-qB/
        rm -rf ./op-qB/tmp

        git clone https://github.com/EasyTier/luci-app-easytier ./op-easytier
        rm -rf ./op-easytier/README.md
        rm -rf ./op-easytier/.github
        rm -rf ./op-easytier/.git
    
        git clone https://github.com/zzsj0928/luci-app-pushbot ./luci-app-pushbot
        rm -rf ./luci-app-pushbo/README.md
        git clone https://github.com/tty228/luci-app-wechatpush ./luci-app-wechatpush
        rm -rf ./luci-app-wechatpush/README.md
        rm -rf ./luci-app-wechatpush/README_en.md
        rm -rf ./luci-app-wechatpush/.github
        # git clone https://github.com/stevenke1981/luci-app-easymesh ./luci-app-easymesh
        # rm -rf ./luci-app-easymesh/README.md
        git clone https://github.com/ilxp/luci-app-ikoolproxy ./luci-app-ikoolproxy
        rm -rf ./luci-app-ikoolproxy/.github
        rm -rf ./luci-app-ikoolproxy/change.log
        rm -rf ./luci-app-ikoolproxy/development.doc
        rm -rf ./luci-app-ikoolproxy/README.md

       
        git clone https://github.com/linkease/nas-packages-luci ./linkease/nas-packages-luci
        mv ./linkease/nas-packages-luci/luci ./linkease/
        rm -rf ./linkease/nas-packages-luci
        
        git clone https://github.com/linkease/nas-packages ./linkease/nas-packages
        mv ./linkease/nas-packages/multimedia/ffmpeg-remux ./linkease/nas-packages/
        mv ./linkease/nas-packages/network/services/* ./linkease/nas-packages/
        rm -rf ./linkease/nas-packages/multimedia
        rm -rf ./linkease/nas-packages/network
        rm -rf ./linkease/nas-packages/.git
        rm -rf ./linkease/nas-packages/README.md
        
        git clone https://github.com/linkease/istore ./linkease/iStore
        mv ./linkease/iStore/luci/*  ./linkease/luci/
        rm -rf ./linkease/iStore

        git clone https://github.com/linkease/istore-ui ./linkease/istore-ui
        mv ./linkease/istore-ui/app-store-ui ./linkease/luci/
        rm -rf ./linkease/istore-ui  

        git clone https://github.com/jjm2473/openwrt-apps ./linkease/openwrt-apps
        mv ./linkease/openwrt-apps/luci-app-mergerfs ./linkease/luci/
        sed -i 's/\.\.\/luci\-alias\.mk/\$\(TOPDIR\)\/feeds\/luci\/luci.mk/g' ./linkease/luci/luci-app-mergerfs/Makefile
        cp -af ./linkease/luci/luci-app-mergerfs/po/zh_Hans ./linkease/luci/luci-app-mergerfs/po/zh-cn
        mv ./linkease/openwrt-apps/mergerfs ./linkease/nas-packages/
        mv ./linkease/openwrt-apps/nvtop ./linkease/nas-packages/
        rm -rf ./linkease/openwrt-apps


        git clone https://github.com/jjm2473/OpenAppFilter ./op-oaf
        rm -rf ./op-oaf/README.md


        ### openlist2
        git clone https://github.com/sbwml/luci-app-openlist2 ./op-openlist2
        rm -rf ./op-openlist2/.git
        rm -rf ./op-openlist2/.github
        rm -rf ./op-openlist2/install.sh
        cp -af ./op-openlist2/luci-app-openlist2/po/zh_Hans ./op-openlist2/luci-app-openlist2/po/zh-cn


        ### smartdns
        # git clone https://github.com/pymumu/luci-app-smartdns ./op-smartdns/luci-app-smartdns
        # rm -rf ./op-smartdns/luci-app-smartdns/.git
        # cp -af ./op-smartdns/luci-app-smartdns/po/zh_Hans ./op-smartdns/luci-app-smartdns/po/zh-cn

        # git clone https://github.com/pymumu/openwrt-smartdns ./op-smartdns/smartdns
        # rm -rf ./op-smartdns/smartdns/.git

   
        git clone https://github.com/xiaorouji/openwrt-passwall-packages ./patch/wall
        rm -rf ./patch/wall/.github
  
        git clone https://github.com/fw876/helloworld ./patch/wall/helloworld
        mv ./patch/wall/helloworld/redsocks2 ./patch/wall/
        mv ./patch/wall/helloworld/lua-neturl ./patch/wall/    
        mv ./patch/wall/helloworld/dns2tcp ./patch/wall/
        mv ./patch/wall/helloworld/dns2socks-rust ./patch/wall/
        mv ./patch/wall/helloworld/trojan ./patch/wall/
        mv ./patch/wall/helloworld/dnsproxy ./patch/wall/      
               
        mv ./patch/wall/helloworld/luci-app-ssr-plus ./patch/wall-luci/
        
        rm -rf ./patch/wall/gn
        mv ./patch/wall/helloworld/gn ./patch/wall/
        # rm -rf ./patch/wall/naiveproxy
        # mv ./patch/wall/helloworld/naiveproxy ./patch/wall/
        rm -rf ./patch/wall/xray-core
        # mv ./patch/wall/helloworld/xray-core ./patch/wall/
        
        rm -rf ./patch/wall/helloworld
    
        git clone https://github.com/xiaorouji/openwrt-passwall ./patch/wall-luci/pass
        git clone https://github.com/xiaorouji/openwrt-passwall2 ./patch/wall-luci/pass2
        mv ./patch/wall-luci/pass/luci-app-passwall ./patch/wall-luci/
        mv ./patch/wall-luci/pass2/luci-app-passwall2 ./patch/wall-luci/
        rm -rf ./patch/wall-luci/pass
        rm -rf ./patch/wall-luci/pass2

        git clone --depth=1 https://github.com/vernesong/OpenClash.git -b dev
        mv ./OpenClash/luci-app-openclash ./patch/wall-luci/
        rm -rf ./OpenClash

        git clone https://github.com/nikkinikki-org/OpenWrt-nikki ./patch/wall-luci/tmp
        mv ./patch/wall-luci/tmp/luci-app-nikki ./patch/wall-luci/
        mv ./patch/wall-luci/tmp/nikki ./patch/wall-luci/
        rm -rf ./patch/wall-luci/tmp


        git clone https://github.com/nikkinikki-org/OpenWrt-momo ./patch/wall-luci/tmp
        mv ./patch/wall-luci/tmp/luci-app-momo ./patch/wall-luci/
        mv ./patch/wall-luci/tmp/momo ./patch/wall-luci/
        rm -rf ./patch/wall-luci/tmp

        
        git clone https://github.com/immortalwrt/homeproxy ./patch/wall-luci/luci-app-homeproxy
        rm -rf ./patch/wall-luci/luci-app-homeproxy/.github
        rm -rf ./patch/wall-luci/luci-app-homeproxy/.git
        
        
        git clone https://github.com/UnblockNeteaseMusic/luci-app-unblockneteasemusic ./luci-app-unblockneteasemusic/
        rm -rf ./luci-app-unblockneteasemusic/.github
        rm -rf ./luci-app-unblockneteasemusic/README.md


        git clone https://github.com/jerrykuku/luci-theme-argon ./theme/luci-theme-argon
        rm -rf ./theme/luci-theme-argon/.github
        rm -rf ./theme/luci-theme-argon/.gitignore     
        rm -rf ./theme/luci-theme-argon/README*
        rm -rf ./theme/luci-theme-argon/RELEASE*
      
        # git clone https://github.com/unifreq/luci-app-oled ./oled
        # mv ./oled/luci-app-oled ./
        # rm -rf ./oled

        git clone https://github.com/gdy666/luci-app-lucky ./op-lucky/tmp
        mv ./op-lucky/tmp/luci-app-lucky ./op-lucky/
        mv ./op-lucky/tmp/lucky ./op-lucky/
        rm -rf ./op-lucky/tmp      

        git clone https://github.com/QiuSimons/luci-app-daed ./op-daed/tmp
        mv ./op-daed/tmp/luci-app-daed ./op-daed/
        mv ./op-daed/tmp/daed ./op-daed/
        rm -rf ./op-daed/tmp
        mkdir -p ./op-daed/libcron && wget -O ./op-daed/libcron/Makefile https://raw.githubusercontent.com/immortalwrt/packages/refs/heads/master/libs/libcron/Makefile
        
        
        git clone https://github.com/sbwml/luci-app-mosdns -b v5 ./op-mosdns/tmp
        mv ./op-mosdns/tmp/luci-app-mosdns ./op-mosdns/
        mv ./op-mosdns/tmp/mosdns ./op-mosdns/
        mv ./op-mosdns/tmp/v2dat ./op-mosdns/
        rm -rf ./op-mosdns/tmp     
        git clone https://github.com/sbwml/v2ray-geodata ./op-mosdns/v2ray-geodata
        
        
    - name: Apply
      run: |
        git add .
        git commit -m "Auto Sync: $(date +%Y-%m-%d" "%H:%M)"
        git push -f 
              
